version: '3'
services:
  ozone:
    image: node:12
    command: yarn dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
    env_file:
     - .env
