version: '3'
services:
  react-server:
    image: node:12
    command: bash -c 'yarn install --ignore-optional && yarn run dev'
    ports:
      - 3001:3000
    volumes:
      - ./react-server/:/usr/src/app
    working_dir: /usr/src/app
    env_file:
     - environment/react-server.env
    networks:
     - nginx_common

networks:
  nginx_common:
    external: true
  